# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool: ToscaServer
- task: CmdLine@2
  displayName: 'Run Tosca CI'
  inputs: 
    script: '$(Agent.HomeDirectory)\\work\\client\\ToscaCIClient.exe -m distributed -t junit -r $(Common.TestResultDirectory)\\ToscaCI.xml'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultFile: '**/ToscaCI*.xml'
    searchFolder: '$(Common.TestResultsDirectory)'
    failTaskOnFailedTests: true
    testRunTitle: 'Publish ToscaCI Test Results'
